In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
# Tensor
a0 = torch.tensor(1.)
a1 = torch.tensor([1., 2. , 3.])
a2 = torch.tensor([[1., 2.], [3., 4.]])

a3 = torch.zeros(3, 4, 5)
a3_one = torch.ones(3, 4, 5)
a3_randn = torch.randn(3, 4, 5)

In [ ]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

torch.Size([3])
torch.Size([2, 2])
torch.Size([3, 4, 5])


In [ ]:
print(a2)
print(a3)
print(a3_one)
print(a3_randn)

tensor([[1., 2.],
        [3., 4.]])
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
tensor([[[ 0.2958, -0.4176,  0.1286,  0.3691,  0.6821],
         [ 0.8082,  0.4023,  0.9453,  0.9458, -0.0526],
         [ 0.4232, -0.0593,  0.3198, -2.9291,  0.6856],
         [-0.8841, -0.3893, -0.5179, -2

In [ ]:
a3_randn.dtype

torch.float32

In [ ]:
tensor_int = torch.tensor([1, 2])
print(tensor_int.dtype)

tensor_bool = torch.tensor([True, False])
print(tensor_bool.dtype)

torch.int64
torch.bool


In [ ]:
a3_randn[0, 1, 4]

tensor(-0.0526)

In [ ]:
print(a3_randn[0, 1, 4])
print(a3_randn[0, 1, :])
print(a3_randn[0, 1, 1:])

tensor(-0.0526)
tensor([ 0.8082,  0.4023,  0.9453,  0.9458, -0.0526])
tensor([ 0.4023,  0.9453,  0.9458, -0.0526])


In [ ]:
a3_randn[0, 1, 4] = 0.26
print(a3_randn[0, 1, 4])

tensor(0.2600)


In [ ]:
print(a3.shape)
a3_reshape = a3.reshape(3, 4*5)
print(a3_reshape.shape)

torch.Size([3, 4, 5])
torch.Size([3, 20])


In [ ]:
print(a3.unsqueeze(0).shape, a3.unsqueeze(1).shape)
print(a3.unsqueeze(0).squeeze(0).shape)

torch.Size([1, 3, 4, 5]) torch.Size([3, 1, 4, 5])
torch.Size([3, 4, 5])


In [ ]:
# batched data
x = torch.randn(10, 3, 32, 32)
x_mlp = x.reshape(10, -1) #x.reshape(10, 3*32*32)

In [ ]:
print(x.device)

cpu


In [ ]:
x = torch.randn(10, 3, 32, 32, device='cuda')
y = torch.randn(10, 3, 32, 32, device='cuda')
print(x.device, y.device)
x + y, x - y, x + 1.

cuda:0 cuda:0


tensor([[[[ 4.5502e-01, -7.0671e-01, -7.1112e-01,  ..., -2.3892e+00,
            3.0229e-01, -1.3786e+00],
          [-1.8972e+00,  1.0339e+00,  3.1256e+00,  ...,  2.5937e-01,
            7.6395e-01,  4.7383e-01],
          [-9.8831e-01,  1.2794e+00, -2.0542e+00,  ..., -3.5525e-01,
            1.5708e+00, -1.7059e+00],
          ...,
          [ 7.6063e-01,  1.4930e+00,  2.1063e+00,  ..., -8.9644e-01,
            4.7007e-01,  1.3150e-01],
          [ 4.3645e-01,  2.1686e+00, -8.2183e-01,  ..., -2.1528e-01,
            7.8774e-01,  1.8903e+00],
          [-3.8681e-01, -8.2957e-01, -2.0112e+00,  ..., -2.6705e+00,
           -8.6798e-01, -1.7336e-01]],

         [[ 3.7453e-01,  5.2200e-01, -1.6930e-01,  ..., -2.1409e+00,
            1.0534e+00, -5.9145e-02],
          [ 3.0996e-01,  1.1720e-01,  3.6672e+00,  ..., -9.5435e-01,
            3.9880e-01, -3.8299e+00],
          [-4.2070e-01, -1.0190e+00,  7.0876e-01,  ..., -1.1541e+00,
           -7.3009e-01,  2.9943e+00],
          ...,
     

In [ ]:
x = torch.randn(10, 3, 32, 32)
y = torch.tensor(3, 32, 32)
x + y
x + y.reshape(1, 3, 32, 32).repeat(10, 1, 1, 1)

In [ ]:
torch.tensor([1, 2]).repeat(3)

tensor([1, 2, 1, 2, 1, 2])

In [ ]:
x = torch.randn(10, 3, 32, 32)
y = torch.randn(10, 3, 32, 32)
z = torch.randn(10, 3, 32, 32)
(x <= y) & (x + 1 < z)

tensor([[[[False, False, False,  ..., False, False, False],
          [False,  True, False,  ..., False, False, False],
          [False, False, False,  ..., False, False,  True],
          ...,
          [False, False, False,  ..., False,  True,  True],
          [False, False,  True,  ..., False, False,  True],
          [False, False, False,  ..., False, False, False]],

         [[False,  True, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [ True, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [ True, False, False,  ...,  True, False, False]],

         [[False, False,  True,  ..., False, False,  True],
          [False, False, False,  ...,  True, False,  True],
          [False, False, False,  ...,  True, False, False],
          ...,
          [False, False, False,  ..., False, False,

In [ ]:
x = torch.randn(2, 5)
# s[i] = x[i][0] + x[i][1] + ... + x[i][4]
print(x)
print(x.sum(dim=1)) #, x.sum(dim=-1)
# mean, max, min
print(x.sum(dim=[0, 1]), x.sum(dim=1).sum(dim=0)) #, x.sum(dim=-1)

tensor([[-1.3571,  1.8907,  1.7268, -0.6006, -1.3224],
        [-0.9462, -0.2672,  0.1340, -0.7108,  0.8781]])
tensor([ 0.3374, -0.9122])
tensor(-0.5748)


In [ ]:
x = torch.tensor(2.)
y = torch.nn.Parameter(torch.tensor(3.))
z = x * y
# torch.autograd.grad(z, y)
z.backward()
print(y.grad)

tensor(2.)
